### ISSUE TITLE
getting java.lang.NoClassDefFoundError on running grails dbm-update

### ISSUE THREAD

**Issue by swzaidi** [grails-plugins/grails-database-migration#145]
Hi! ,

I have a grails 3.3.6 setup and trying to run dbm-update for liquibase migration. In doing so i am getting the following exception...

```
rror during conversion: java.lang.NoClassDefFoundError: org/codehaus/groovy/grails/commons/ApplicationAttributes^[[0K

java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/codehaus/groovy/grails/commons/ApplicationAttributes
        at org.codehaus.groovy.control.CompilationUnit.convertUncaughtExceptionToCompilationError(CompilationUnit.java:1123)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1101)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:174)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:56)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:73)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:64)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:29)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerDaemonServer.execute(AbstractDaemonCompiler.java:91)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


----

Please let me know of any pointers to resolve this issue

THanks
Shiraz

**Comment by puneetbehl** [comment]
Try `./gradlew dbmUpdate`.

**Comment by puneetbehl** [comment]
I am able to run both `./gradlew dbmUpdate` and `./grailsw dbm-update`. Please try with the below application.
[myapp.zip](https://github.com/grails-plugins/grails-database-migration/files/2305017/myapp.zip)

*NOTE:* Update Mysql credentials in `application.yml`.

**Comment by niravassar** [comment]
I tried the app here on 3.3.6, and also on another sample app. It also works on 4.0.0.BUILD-SNAPSHOT. I am closing this, if some other issue arises concerning this please let us know.
