### ISSUE TITLE
Possible plugin load order issue

### ISSUE THREAD

**Issue by ctoestreich** [grails-plugins/grails-database-migration#42]
Trying to run some of the dbm* commands produces an odd issue where a domain class is using springSecurityService

```
java.lang.NullPointerException: Cannot invoke method encodePassword() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.5.jar:2.4.5]
	at com.lunchify.auth.User.encodePassword(User.groovy:88) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
```

```
protected void encodePassword() {
		println '<<<<<<<<<>>>>>>>>>'
		println springSecurityService.encodePassword(password)
        password = springSecurityService ? springSecurityService.encodePassword(password) : password
    }
```

This issue only came up due to me attempting to use the SSS in a println, but it might want to be changed in this plugin to loadafter spring-security-core

**Comment by bwagner5** [comment]
It looks like it's trying to run Bootstrap.groovy. I tried a `grails dbm-drop-all` and it prints out my Bootstrap logs and fails because the scripts I have running in Bootstrap are failing.

**Comment by KerchumA222** [comment]
This isn't restricted to Spring-Security. I have a database seed that only runs when the environment is `Environment.DEVELOPMENT`, and it tries to seed on any dbm* command. 
This means that when I change a domain that gets seeded I have to go to my `SeederBootStrap.groovy` and comment everything out.

**Comment by KerchumA222** [comment]
Will this ever be fixed?

**Comment by Schlogen** [comment]
I'm going to close this and create a more descriptive issue, which is a feature request in grails-core to allow commands to skip the Bootstrap process

**Comment by Schlogen** [comment]
Relevant issue https://github.com/grails/grails-core/issues/10022

**Comment by zyro23** [comment]
i guess #78 can be closed then as well?

**Comment by edwardotis** [comment]
@ctoestreich I'm having the a similar problem calling User.encodePassword() from within a dbm changeSet. The springsecurityservice bean used for encoding is not injected into User in grails 3.1, but it was injected properly in grails 2.5.5 during dbm-update 

How did you get past this issue?

Grails 3.1.14
database-migration:2.0.0
spring-security-core:3.1.1
