### ISSUE TITLE
Connection creation fails with Grails 3.1.0 in GrailsLiquibase -class

### ISSUE THREAD

**Issue by smakela** [grails-plugins/grails-database-migration#49]
There is not method anymore that accepts only connection as you see:

https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/integration/spring/SpringLiquibase.java

Caused by: java.lang.NoSuchMethodError: liquibase.integration.spring.SpringLiquibase.createDatabase(Ljava/sql/Connection;)Lliquibase/database/Database;
	at org.grails.plugins.databasemigration.liquibase.GrailsLiquibase.createDatabase(GrailsLiquibase.groovy:62) ~[database-migration-2.0.0.RC1.jar:na]
	at org.grails.plugins.databasemigration.liquibase.GrailsLiquibase.createLiquibase(GrailsLiquibase.groovy:45) ~[database-migration-2.0.0.RC1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:389) ~[liquibase-core-3.4.2.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 21 common frames omitted

**Comment by graemerocher** [comment]
Seems like you need to use a version of Liquibase that is compatible with the plugin in that case.

**Comment by graemerocher** [comment]
Try add
 
      compile 'org.liquibase:liquibase-core:3.3.2'

To your project dependencies

**Comment by smakela** [comment]
Yep. That worked of course. That should be in the documetation (maximum luiquibase-core version).

**Comment by graemerocher** [comment]
Updated https://github.com/grails-plugins/grails-database-migration/commit/b2915891627589b0e664269bb844f13bc86ea22c

**Comment by smakela** [comment]
That's a wrap!

**Comment by davydotcom** [comment]
tried this on 3.1.5 still getting the error

**Comment by davydotcom** [comment]
Caused by: java.lang.NoSuchMethodError: liquibase.integration.spring.SpringLiquibase.createDatabase(Ljava/sql/Connection;Lliquibase/resource/ResourceAccessor;)Lliquibase/database/Database;

I specified 3.3.2 and confirmed the dependencies tree on the app running database migrations plugin  2.0.0.RC4

**Comment by mugdho** [comment]
2.0.0.RC4 is a further upgrade on Liquibase. So 3.3.2 doesnt work. Instead add liquibase core 3.4.1 and your code should start working. We should probably update the plugin with the right liquibase version.
