### ISSUE TITLE
"Another unnamed CacheManager" - issue after dbm-update

### ISSUE THREAD

**Issue by vahurh** [grails-plugins/grails-database-migration#62]
After running prod-dbm-update on my Grails 3.1.4 application with 2.0.0.RC1 version of the plugin, I started getting this error when deploying WAR to AWS:

`Caused by: org.hibernate.cache.CacheException: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.`

I've seen other people running into this issue with Grails 2.5.0, their solution being switching the default echache factory to: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory ( [http://peedeebeesblog.blogspot.com.ee/2015/06/moving-up-grails-243-to-250.html](http://peedeebeesblog.blogspot.com.ee/2015/06/moving-up-grails-243-to-250.html) ). After doing this change, I started getting this error:

`java.lang.IllegalStateException: Cannot find changelog location: class path resource [db/changelog/db.changelog-master.yaml] (please add changelog or check your Liquibase configuration)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
`
I do have this in my build.gradle:
`sourceSets {
	main {
		resources {
			srcDir 'grails-app/migrations'
		}
	}
}`

In total I've done 3 dbm-updates: generating a database from a changelog, adding a few columns and now the latest one. The first two worked perfectly, the third one resulted in this issue. 

I've also tried  turning off second level cache, running new dbm-updates, disabling liquibase in application.yml, disabling liquibase "check-change-log-location" option, terminating and re-creating the AWS EC2 instance - nothing has worked so far.

I'm running out of ideas - do you think the dbm-update might have caused this? Do you have any suggestions on how to fix it?

**Comment by sergiodelamoshoptimix** [comment]
I've been having the same issues in the past days while deploying a war file to production. I installed the spring security core plugin and spring security rest plugin and began to get a miriad of errors when deploying the war.  Everything worked fine in dev. I had a multiproject build with several grails projects with the web-plugin profile  and a grails app with the web profile.  I was having the issues running in 3.0.15 or in 3.1.4

My solution has been to put everything together in a single web profile proyect no multi project. If that it is an option for you check it out.

**Comment by sergiodelamoshoptimix** [comment]
I was deploying to a tomcat installed in an AWS EC2 through elastic beanstalk but I have been able to reproduce it deploying the war file in a tomcat in my laptop.

**Comment by vahurh** [comment]
It's reassuring to read that others are having similar problems!

Mine is a single project, built with the new AngularJS profile. And I'm also using the Spring Security + Spring Security Rest plugin. And deploying to Elastic Beanstalk. Everything works fine in dev.

Btw once I set liquibase.enabled to false, I started getting this:
`
Caused by: org.grails.core.exceptions.GrailsConfigurationException: Error configuring dynamic methods for plugin [springSecurityCore:3.0.3]: null
	at grails.plugins.DefaultGrailsPluginManager.doDynamicMethods(DefaultGrailsPluginManager.java:714)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:227)
	at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:387)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
	at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:149)
	at org.grails.boot.context.web.GrailsAppServletInitializer.createRootApplicationContext(GrailsAppServletInitializer.groovy:57)
	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5244)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more`

**Comment by sdelamo** [comment]
@vahurh please note there is another version of the plugin 2.0.0.RC4

**Comment by vahurh** [comment]
Hey - tried the same thing with version 2.0.0.RC4 - still the exact same issue. When using EhCacheRegionFactory, I get the "Another unnamed CacheManager already exists"-error and SingletonEhCacheRegionFactory seems to fix the CacheManager issue, but still triggers the "Cannot find changelog location: class path resource [db/changelog/db.changelog-master.yaml]"-issue. 

Is there a config change I'm missing? Should it even check the changelog location on start? Doesn't Grails' dbm have updateOnStart = false as a default?

**Comment by vahurh** [comment]
This doesn't seem to be an issue with this plugin. Haven't yet figured out the solution, but the same problem arises with an app that hasn't done any migrations on a new EB instance.

**Comment by vahurh** [comment]
(Just in case anyone else encounters this error and ends up here). For me this was an issue with the AWS SDK plugin for Grails 3 ( https://github.com/agorapulse/grails-aws-sdk/tree/grails3 ). Reverting all my changes and just replacing the plugin with the AWS SDK for Java through Gradle fixed the issue. Sorry for spamming!

**Comment by edwardotis** [comment]
For posterity, I had a similar issue  onElasticBeanstalk with grails 3.x and tomcat.
I set this property in application.groovy to fix it:
liquibase.enabled = false

Of course, you'll have to unset that when you actually want to do a migration, but just run that from a non beanstalk/tomcat machine.
