### ISSUE TITLE
error loading migrations from 1.x with comment() sections 

### ISSUE THREAD

**Issue by j4y** [grails-plugins/grails-database-migration#90]
I'm working on a grails project that is upgrading from grails 2.x to 3.  It's failing with migrations that have the comment section like this:

```
	changeSet(author: "j4y", id: "1357154800847-1") {
        comment("Adding partner record because...")
        sql("INSERT INTO partner(...)")
	}
```

error running 2.0.0RC4 with grails 3.0.17:

```
INFO 10/7/16 1:58 PM: liquibase: Successfully released change log lock
WARN org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springLiquibase_dataSource': Invocation of init method failed; nested exception is liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: org.grails.plugins.databasemigration.DatabaseMigrationException: Unknown method name: comment
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1572) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:759) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480) ~[spring-context-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:117) [spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:689) [spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) [spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:55) [grails-core-3.0.17.jar:3.0.17]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:374) [grails-core-3.0.17.jar:3.0.17]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:363) [grails-core-3.0.17.jar:3.0.17]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-2.4.5.jar:2.4.5]
	at affdex.portal.Application.main(Application.groovy:8) [main/:na]
Caused by: liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: org.grails.plugins.databasemigration.DatabaseMigrationException: Unknown method name: comment
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:27) ~[liquibase-core-3.4.2.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:227) ~[liquibase-core-3.4.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:202) ~[liquibase-core-3.4.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:192) ~[liquibase-core-3.4.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434) ~[liquibase-core-3.4.2.jar:na]
	at org.grails.plugins.databasemigration.liquibase.GrailsLiquibase.performUpdate(GrailsLiquibase.groovy:80) ~[database-migration-2.0.0.RC4.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391) ~[liquibase-core-3.4.2.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1631) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1568) ~[spring-beans-4.1.8.RELEASE.jar:4.1.8.RELEASE]
	... 20 common frames omitted
Caused by: liquibase.exception.SetupException: org.grails.plugins.databasemigration.DatabaseMigrationException: Unknown method name: comment
```

If I remove all of the `comment()` lines from the 1.x migrations it works as expected.  I thought modifying previous migrations was a no-no, but it looks like it doesn't complain.  The 1.x version used to raise a checksum error.

**Comment by jameskleeh** [comment]
I can't reproduce this. Create a new issue if this is still happening with `2.0.0.BUILD-SNAPSHOT`
